# Generated by Django 3.1.4 on 2020-12-23 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apitest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apitestname', models.CharField(max_length=64, verbose_name='娴佺▼鎺ュ彛鍚嶇О')),
                ('apitestdesc', models.CharField(max_length=64, null=True, verbose_name='鎻忚堪')),
                ('apitester', models.CharField(max_length=16, verbose_name='娴嬭瘯璐熻矗浜�')),
                ('apitestresult', models.BooleanField(verbose_name='娴嬭瘯缁撴灉')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='鍒涘缓鏃堕棿')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': '娴佺▼鍦烘櫙鎺ュ彛',
                'verbose_name_plural': '娴佺▼鍦烘櫙鎺ュ彛',
            },
        ),
        migrations.CreateModel(
            name='Apistep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiname', models.CharField(max_length=100, verbose_name='鎺ュ彛鍚嶇О')),
                ('apiurl', models.CharField(max_length=200, verbose_name='url 鍦板潃')),
                ('apiparamvalue', models.CharField(max_length=800, verbose_name='璇锋眰鍙傛暟鍜屽��')),
                ('apimethod', models.CharField(choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('delete', 'delete'), ('patch', 'patch')], default='get', max_length=200, null=True, verbose_name='璇锋眰鏂规硶')),
                ('apiresult', models.CharField(max_length=200, verbose_name='棰勬湡缁撴灉')),
                ('apistep', models.CharField(max_length=100, null=True, verbose_name='娴嬭瘯姝ヨ仛')),
                ('apistatus', models.BooleanField(verbose_name='鏄\ue21a惁閫氳繃')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='鍒涘缓鏃堕棿')),
                ('Apitest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.apitest')),
            ],
        ),
    ]
