# Generated by Django 3.1.4 on 2020-12-24 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apitest',
            options={'verbose_name': '流程场景接口', 'verbose_name_plural': '流程场景接口'},
        ),
        migrations.AlterField(
            model_name='apistep',
            name='apimethod',
            field=models.CharField(max_length=200, verbose_name='方法'),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='apiname',
            field=models.CharField(max_length=100, verbose_name='接口名称'),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='apiparamvalue',
            field=models.CharField(max_length=800, verbose_name='请求参数和值'),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='apiresult',
            field=models.CharField(max_length=200, verbose_name='预期结果'),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='apistatus',
            field=models.BooleanField(verbose_name='是否通过'),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='apistep',
            field=models.CharField(max_length=100, null=True, verbose_name='测试步聚'),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='apiurl',
            field=models.CharField(max_length=200, verbose_name='url 地址'),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='apitest',
            name='apitestdesc',
            field=models.CharField(max_length=64, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='apitest',
            name='apitester',
            field=models.CharField(max_length=16, verbose_name='执行人'),
        ),
        migrations.AlterField(
            model_name='apitest',
            name='apitestname',
            field=models.CharField(max_length=64, verbose_name='流程接口名称'),
        ),
        migrations.AlterField(
            model_name='apitest',
            name='apitestresult',
            field=models.BooleanField(verbose_name='测试结果'),
        ),
        migrations.AlterField(
            model_name='apitest',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.CreateModel(
            name='Apis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiname', models.CharField(max_length=100, verbose_name='接口名称')),
                ('apiurl', models.CharField(max_length=200, verbose_name='url 地址')),
                ('apiparamvalue', models.CharField(max_length=800, verbose_name='请求参数和值')),
                ('apimethod', models.CharField(choices=[('0', 'get'), ('1', 'post'), ('2', 'put'), ('3', 'delete'), ('4', 'patch')], default='0', max_length=200, verbose_name='请求方法')),
                ('apiresult', models.CharField(max_length=200, verbose_name='预期结果')),
                ('apistatus', models.BooleanField(verbose_name='是否通过')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': '单一场景接口',
                'verbose_name_plural': '单一场景接口',
            },
        ),
    ]
